### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement requirements.txt

### ISSUE THREAD

**Issue by jackieburkhart** [vExo307/xboxdiscordrpc#2]
![gitissue](https://user-images.githubusercontent.com/49613637/105129831-1ed7de00-5b10-11eb-8133-e771ae01e5a8.PNG)

Maybe something is outdated?

**Comment by vExo307** [comment]
I have updated the readme to fix the issue, it was a mistype on my part.
Instead of:
pip3 install requirements.txt 
You need:
pip3 install -r requirements.txt
